### ISSUE TITLE
Feature Request: ability to run shell command right after "ok google" hotword

### ISSUE THREAD

**Issue by elissonm** [Shrugs/Googiri#1]
First I'd like to thank you for your hard working creating such a wonderful tweak.
It would be awesome if you could add this feature I described at the topic. It would enable me for example to send a mute command to my tv and other multimedia devices right after I say the hotword "Ok Google" so that it could understand my next command better.

**Comment by shrugs** [comment]
Thank you for using Googiri!

Do you want to run a shell command on your phone or to run a shell command on the webserver that Googiri is communicating with?

**Comment by elissonm** [comment]
In my particular case I need it on my phone. It might be easier to implement a trigger to an Activator action. I could call a shell command from Activator then. Other people might need this for a webserver though. BTW, Thanks for the prompt response.

**Comment by shrugs** [comment]
Oh I see, that's a pretty cool idea.

I don't have my macbook until June (I'm traveling with a chromebook right now), so I can't update Googiri until then.

But if you have the ability to develop jailbreak tweaks, I could help you implement it.

[Line 249](https://github.com/Shrugs/Googiri/blob/master/Tweak.xm#L249) is called when the "speech to text view" is opened (after you say "OK google" or tap the voice icon). So to execute an Activator action, you could put 

``` objc
NSString *activatorListener = @"com.something.whatever"
CPDistributedMessagingCenter *messagingCenter = [%c(CPDistributedMessagingCenter) centerNamed:@"com.mattcmultimedia.googirisiriactivator"];
rocketbootstrap_distributedmessagingcenter_apply(messagingCenter);
[messagingCenter
                      sendMessageName:@"googiriActivateActivatorWithListener"
                      userInfo:[NSDictionary dictionaryWithObjectsAndKeys: activatorListener, @"listener", nil]];
```

Then the `googirisiriactivator` process with see that message and execute your activator listener.

I'm sorry I can't update Googiri soon!

**Comment by elissonm** [comment]
I've been able to develop some very basic tweaks. Nothing as complex as Googiri though. I could probably do it with your help, but I don't even know how to fix some errors I'm having with SCLAlertView when trying to compile Googiri. I tried older releases of SCLAlertView (0.40; 0.80) but I keep getting these errors:

`In file included from Tweak.xm:3:
In file included from /Users/elissonm/Downloads/Tweaks/Googiri/Tweak.h:69:
In file included from /Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:14:
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLButton.h:74:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property id target;
^
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLButton.h:74:1: error: default property attribute 'assign' not appropriate for non-GC object [-Werror,-Wobjc-property-no-attribute]
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLButton.h:94:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property (nonatomic) SCLTimerDisplay *timer;
^
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLButton.h:94:1: error: default property attribute 'assign' not appropriate for non-GC object [-Werror,-Wobjc-property-no-attribute]
In file included from Tweak.xm:3:
In file included from /Users/elissonm/Downloads/Tweaks/Googiri/Tweak.h:69:
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:108:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property UILabel *labelTitle;
^
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:108:1: error: default property attribute 'assign' not appropriate for non-GC object [-Werror,-Wobjc-property-no-attribute]
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:114:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property UITextView *viewText;
^
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:114:1: error: default property attribute 'assign' not appropriate for non-GC object [-Werror,-Wobjc-property-no-attribute]
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:120:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property UIActivityIndicatorView *activityIndicatorView;
^
/Users/elissonm/Downloads/Tweaks/Googiri/SCLAlertView/SCLAlertView/SCLAlertView.h:120:1: error: default property attribute 'assign' not appropriate for non-GC object [-Werror,-Wobjc-property-no-attribute]
10 errors generated.
make[3]: *** [/Users/elissonm/Downloads/Tweaks/Googiri/.theos/obj/debug/armv7/Tweak.xm.e1343968.o] Error 1
make[2]: *** [/Users/elissonm/Downloads/Tweaks/Googiri/.theos/obj/debug/armv7/Googiri.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [Googiri.all.tweak.variables] Error 2
`

**Comment by shrugs** [comment]
Looks like just some compiler warnings (it's assuming we want `assign` for the attribute on those properties) and theos treats all warnings as errors, so it's failing to build. If you manually edit the lines it's complaining about to use `assign` or `retain`, it should be good to go. `retain` is for pointers to object types (like NSString or whatever) and `assign` is for value types like `bool`. So if you manually edit those lines with the right properties the warnings should go away.

**Comment by elissonm** [comment]
I thought I had the wrong SCLAlertView or something else. After fixing these files and adding Googiri_LIBRARIES += substrate rocketbootstrap to the Makefile, I finally managed to compile Googiri with the added feature. Thank you very much!

**Comment by shrugs** [comment]
Awesome!! So glad it's working for you.
