### ISSUE TITLE
reListen: true causes Google crash

### ISSUE THREAD

**Issue by anned20** [Shrugs/Googiri#2]
Like the tile says: sending a json object with reListen: true back causes the Google app to crash.
I was trying to make a 'Are you sure?' type of thing.

Other than this: **_This is awesome!_**

anned20

**Comment by shrugs** [comment]
Thanks for using Googiri, and thanks for your patience; it took me a while to respond to this cause of other responsibilities.

I may have some time to debug this later this week.

Can you tell me if you're sending back a boolean `true` or the word `"true"` as a string? Googiri supports a JSON boolean for `reListen`, which looks like:

```
{
  reListen: true
}
```

**Comment by anned20** [comment]
I tried both. I am using Googiri to turn on/off my TV

**Comment by shrugs** [comment]
Awesome thanks for the info. I'll try this out tomorrow with the latest build of Google and see if I can reproduce.
